- Testing a new reporter

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -19,10 +19,15 @@ jobs:
       run: npx playwright install --with-deps
     - name: Run Playwright tests
       run: npx playwright test
-    - name: Publish JUnit report
-      uses: actions/upload-artifact@v4
-      if: ${{ !cancelled() }}
+    # - name: Publish JUnit report
+    #   uses: actions/upload-artifact@v4
+    #   if: ${{ !cancelled() }}
+    #   with:
+    #     name: '**/pw-junit-test-results.xml'
+    #     path: .
+    #     retention-days: 30
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
       with:
-        name: pw-junit-test-results.xml
-        path: .
-        retention-days: 30
+        report_paths: '**/pw-junit-test-results.xml'
